spring.application.name=worldcup2026

# Server
server.port=${PORT:8080}

# Postgresql - VPS
spring.datasource.url=jdbc:postgresql://5.10.251.145:5432/sport_predictor
spring.datasource.username=predictor
spring.datasource.password=Marianxx70psql
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Thymeleaf
spring.thymeleaf.cache=false
